# this script initializes all packages needed for this project
# we use renv to lock packages and create a reproducible data flow
# refer to https://rstudio.github.io/renv/articles/renv.html for renv usage

# library installation ====
renv::install("tidyverse") # general tools for data manipulation
renv::install("terra")     # a newer spatial package? doesn't seem like the best
renv::install("raster")    # used to import and work with raster data
renv::install("sf")        # used for gis vector data manipulation
renv::install("tidyterra") # tidyverse support for terra objects

# this installs the following libraries:
# - askpass       [1.2.1]
# - backports     [1.5.0]
# - base64enc     [0.1-3]
# - bit           [4.6.0]
# - bit64         [4.6.0-1]
# - blob          [1.3.0]
# - broom         [1.0.11]
# - bslib         [0.9.0]
# - cachem        [1.1.0]
# - callr         [3.7.6]
# - cellranger    [1.1.0]
# - cli           [3.6.5]
# - clipr         [0.8.0]
# - conflicted    [1.2.0]
# - cpp11         [0.5.2]
# - crayon        [1.5.3]
# - curl          [7.0.0]
# - data.table    [1.18.0]
# - DBI           [1.2.3]
# - dbplyr        [2.5.1]
# - digest        [0.6.39]
# - dplyr         [1.1.4]
# - dtplyr        [1.3.2]
# - evaluate      [1.0.5]
# - farver        [2.1.2]
# - fastmap       [1.2.0]
# - fontawesome   [0.5.3]
# - forcats       [1.0.1]
# - fs            [1.6.6]
# - gargle        [1.6.0]
# - generics      [0.1.4]
# - ggplot2       [4.0.1]
# - glue          [1.8.0]
# - googledrive   [2.1.2]
# - googlesheets4 [1.1.2]
# - gtable        [0.3.6]
# - haven         [2.5.5]
# - highr         [0.11]
# - hms           [1.1.4]
# - htmltools     [0.5.9]
# - httr          [1.4.7]
# - ids           [1.0.1]
# - isoband       [0.3.0]
# - jquerylib     [0.1.4]
# - jsonlite      [2.0.0]
# - knitr         [1.51]
# - labeling      [0.4.3]
# - lifecycle     [1.0.5]
# - lubridate     [1.9.4]
# - magrittr      [2.0.4]
# - memoise       [2.0.1]
# - mime          [0.13]
# - modelr        [0.1.11]
# - openssl       [2.3.4]
# - pillar        [1.11.1]
# - pkgconfig     [2.0.3]
# - prettyunits   [1.2.0]
# - processx      [3.8.6]
# - progress      [1.2.3]
# - ps            [1.9.1]
# - purrr         [1.2.1]
# - R6            [2.6.1]
# - ragg          [1.5.0]
# - rappdirs      [0.3.3]
# - RColorBrewer  [1.1-3]
# - readr         [2.1.6]
# - readxl        [1.4.5]
# - rematch       [2.0.0]
# - rematch2      [2.1.2]
# - reprex        [2.1.1]
# - rlang         [1.1.7]
# - rmarkdown     [2.30]
# - rstudioapi    [0.17.1]
# - rvest         [1.0.5]
# - S7            [0.2.1]
# - sass          [0.4.10]
# - scales        [1.4.0]
# - selectr       [0.5-1]
# - stringi       [1.8.7]
# - stringr       [1.6.0]
# - sys           [3.4.3]
# - systemfonts   [1.3.1]
# - textshaping   [1.0.4]
# - tibble        [3.3.1]
# - tidyr         [1.3.2]
# - tidyselect    [1.2.1]
# - tidyverse     [2.0.0]
# - timechange    [0.3.0]
# - tinytex       [0.58]
# - tzdb          [0.5.0]
# - utf8          [1.2.6]
# - uuid          [1.2-1]
# - vctrs         [0.6.5]
# - viridisLite   [0.4.2]
# - vroom         [1.6.7]
# - withr         [3.0.2]
# - xfun          [0.55]
# - xml2          [1.5.1]
# - yaml          [2.3.12]

# note: use renv::update() to get latest versions of all dependencies
# note: use renv::snapshot() to update snapshot of used packages

# folder creation ====
dir.create("./output")
dir.create("./output/plots")
dir.create("./output/data_out")
